### PR TITLE
Support Strict Concurrency

### PR DESCRIPTION
**Pull request by bauer-andreas**
# Support Strict Concurrency

## :recycle: Current situation & Problem
This PR enables strict concurrency for the ResearchKitSwiftUI targets. Swift 6 is now fully supported.

## :gear: Release Notes 
* Compatibility with Swift 6

## :books: Documentation
--

## :white_check_mark: Testing
--

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Looks great; thank you @Supereg!

**Comment by bauer-andreas** [comment]
Just saw that this PR isn't merged yet. Could you force merge this PR @PSchmiedmayer? I currently do not have the permission for that. Codecov sadly wasn't able to provide codecov results after two attempts.

**Comment by bauer-andreas** [comment]
It seems like the main branch never collected any coverage reports? Also the last few PRs also didn't collect any coverage. Maybe it is a configuration issue?

**Comment by bauer-andreas** [comment]
@PSchmiedmayer I updated the build_and_test action to also run on a push to main. This should ensure code coverage will work in the future.

**Comment by PSchmiedmayer** [comment]
Sure; thanks for the reminder! I just merged the PR 👍

**Comment by bauer-andreas** [comment]
thank you 🚀

**Pull request merged**
